ci: Retry installing snapcraft up to 10 times before giving up
The snapcraft server is not reliable at all. We usually get it to respond after 2 or 3 tries. This should get rid of our problems.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -114,7 +114,16 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y --fix-missing snapd
-          sudo snap install snapcraft --classic
+          for i in {1..10}; do
+            if sudo snap install snapcraft --classic; then
+              break
+            elif [ $i -eq 10 ]; then
+              exit 1
+            else
+              echo "Retry $i failed, waiting 30s..."
+              sleep 30
+            fi
+          done
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
